# This is a basic workflow to help you get started with Actions

name: Submodule Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
    # Checkout this repo with token, along with its private submodules
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    # Runs a single command using the runners shell
    - name: Check what was checked out
      run: |
        ls -lah .
        ls -lah ./scaling-waddle
        cat ./scaling-waddle/README.md

